language: python

cache: pip

python:
  - "2.7"
  - "3.7"
  - "3.8"

env:
- ANSIBLE_VER="ansible<2.9"
- ANSIBLE_VER="ansible>=2.9"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install git
  - pip install "$ANSIBLE_VER"
  - make setup

script:
  - make test
