language: python

cache: pip

python:
  - "2.7"
  - "3.7"
  - "3.8"

env:
- ANSIBLE="<2.8"
- ANSIBLE=">=2.9"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install git
  - echo "$ANSIBLE"
  - pip install "ansible$ANSIBLE"
  - make setup

script:
  - make test
